```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggrepel)
library(tidyverse)
library(skimr)

install.packages("Rtsne")
library(Rtsne)

install.packages("viridis")  # Install
library("viridis")  

set.seed(145804)
```


```{r}
data <- read_csv("./Data/spotify_analysis.csv")
print(paste("Max. perplexity", ((data |> nrow() - 1)/3) |> round(0)))
```

```{r}
 sin_lineas <- theme(panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank())
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=6000, scale=TRUE)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = year)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=6000, scale=TRUE, perplexity=10)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(500)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=1000, scale=TRUE, perplexity=100)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```


```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=4000, scale=TRUE, perplexity=100)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=1000, scale=TRUE, perplexity=500)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=5000, scale=TRUE, perplexity=200)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=5000, scale=TRUE, perplexity=50)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=3000, scale=TRUE, perplexity=5)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=3000, scale=TRUE, perplexity=8)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=5000, scale=TRUE, perplexity=5)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```

```{r}
music <- data[,c(7:16)]
data2 <- data %>%  mutate(duplicated = music %>% duplicated()) %>% filter(duplicated==FALSE)
music2 <- data2[,c(7:16)]


tsne_music <- Rtsne(music2, max_iter=5000, scale=TRUE, perplexity=20)
tsne_music_Y <- tsne_music$Y




colnames(tsne_music_Y) <- c("V1", "V2")
dat_tsne <- as_tibble(tsne_music_Y )
dat_tsne$name <- as.character(data2$name)
dat_tsne$top_500 <- data2$top_500
dat_tsne$year<- data2$year

dat_tsne <- rbind(
              dat_tsne |> filter(top_500 == TRUE),
              dat_tsne |> filter(top_500 == FALSE) |> sample_n(300)
)

ggplot(dat_tsne, aes(x=V1, y=V2,  colour = top_500)) + geom_point() + theme_minimal() 
```
